AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  employee

  Sample SAM Template for employee
Globals:
  Function:
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          EMPLOYEE: !Ref EmployeesTable
          DUMMY_TABLE: !Ref DummyTable

Resources:
  EmployeesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  DummyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
  StandardSqsQueue:
    Type: AWS::SQS::Queue
  GetEmployeeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: employee
      Handler: com.lambda.GetEmployee::getEmployee
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
      Events:
        EmployeeEvent:
          Type: Api
          Properties:
            Path: /employee/{id}
            Method: GET
  AddEmployeeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: employee
      Handler: com.lambda.AddEmployee::addEmployee
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
      Events:
        EmployeeEvent:
          Type: Api
          Properties:
            Path: /employee
            Method: POST
  DeleteEmployeeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: employee
      Handler: com.lambda.DeleteEmployee::deleteEmployee
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
      Events:
        EmployeeEvent:
          Type: Api
          Properties:
            Path: /employee/{id}
            Method: DELETE
  GetAllEmployeeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: employee
      Handler: com.lambda.GetAllEmployees::getAllEmployees
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
      Events:
        EmployeeEvent:
          Type: Api
          Properties:
            Path: /allemployees
            Method: GET
  AddEmployeesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: employee
      Handler: com.lambda.AddEmployees::addEmployees
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DummyTable
      Events:
        EmployeeEvent:
          Type: Api
          Properties:
            Path: /employees
            Method: POST
  StandardSqsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: employee
      Handler: com.lambda.sqs.StandardSqs::addEmployeesSqs
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EmployeesTable
      Events:
        SQSEmployeeEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt StandardSqsQueue.Arn
            BatchSize: 10


